# Generated by Django 6.0.5 on 2026-05-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('electricity', 'Electricity'), ('travel', 'Corporate Travel')], max_length=30)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct fuel combustion'), ('scope_2', 'Scope 2 — Purchased electricity'), ('scope_3', 'Scope 3 — Business travel')], max_length=10)),
                ('activity_type', models.CharField(max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('record_date', models.DateField()),
                ('quantity_raw', models.FloatField()),
                ('unit_raw', models.CharField(max_length=50)),
                ('quantity_normalised', models.FloatField()),
                ('unit_normalised', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('co2_kg', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged — needs attention'), ('approved', 'Approved — locked for audit'), ('rejected', 'Rejected — excluded from totals')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('werks', models.CharField(max_length=10, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('electricity', 'Electricity'), ('travel', 'Corporate Travel')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(default='analyst', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('flagged', 'Auto-flagged on ingest')], max_length=20)),
                ('performed_by', models.CharField(default='analyst', max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='upload_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.uploadbatch'),
        ),
    ]
