# Generated by Django 6.0.5 on 2026-05-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_seed_plant_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='row_hash',
            field=models.CharField(db_index=True, default='', help_text='MD5 hash for duplicate detection', max_length=64),
        ),
    ]
